# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2655577f1a9c8b72f29e71361a4c1c2dd34a7e6ecaafdc17abdac2cc4aa9c1e0e0de8b76cd7e1378ffc95ea13c046df7714bd4584cf9926dad08d78226b2718

test:
  secret_key_base: fe3845c17740cd6c1d2cedededdd15f9babb562f6911d242e1e554ad408884ef06e883d2326fc5b7bb6a4112ff9f7472edb29491f9a40cf15ee962bbaf3d87ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
